### ISSUE TITLE
UserRight Assignments not idempotent

### ISSUE THREAD

**Issue by ripclawffb** [ayohrling/local_security_policy#27]
Has anyone else had the issue where puppet keeps re-applying the user right assignments over and over? It looks like when the user rights are exported, they are exported as SIDs  instead of usernames via the secedit tool. I have am supplying the username when I call the puppet type. The policy is updated properly, but it gets applied on every run.

**Comment by natemccurdy** [comment]
Yes, running into this same issue here @ripclawffb

**Comment by RARYates** [comment]
Is it a built-in user (Such as Guest or Administrator) or a custom user?

**Comment by ripclawffb** [comment]
It's an Active Directory account.

**Comment by natemccurdy** [comment]
@RARYates It only happens for custom accounts, not built-in accounts.

**Comment by natemccurdy** [comment]
This is likely a duplicate of #14

**Comment by brownken** [comment]
I noticed this during some puppet learning sessions past couple of weeks.   Note:  I'm still learning puppet - so please excuse me if I mis-state something or use the wrong terms!

For domain joined computers, the actual data stored on the computer for user rights (or in local groups) are stored as the object's SID (either a well known SID for local objects or domain SID's for domain joined machines). 

When puppet is comparing state, the LSP module is apparently submitting friendly names ("domain\user1, domain\user2") and that doesn't compare directly to the object's SID stored in the appropriate computer's object; since they don't match, puppet then applies the changes (and reapplies them each puppet run) - and the changes do convert the supplied friendly names to the SID's to be stored.

I don't know how to fix this;  we did discuss a potential work around: submit SIDs via the LSP Module and not the friendly "domain\user1" name.  That is not "coder friendly" and isn't readable in the puppet code without documenting each SID/friendly name for each right being updated.  (new thought: maybe there is a "function"/class that can be used to convert the friendly names to SID's that can have a "depends on" that the LSP module can use as a parameter?)

Using the SID's is a work-around we discussed when troubleshooting the WMIC bug (that Thomas Linkin submitted as part of the 0.6.2 release affecting a domain joined machine).

**Comment by AndyAdrian-OP** [comment]
The ability to use user or group names was added in https://github.com/ayohrling/local_security_policy/pull/99.
